version: '3.8'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    # The port is no longer exposed to the host.
    # Nginx will access it via the internal Docker network.

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80" # Expose port 80 to the host
    volumes:
      - ./frontend:/usr/share/nginx/html # Mount frontend files
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mount nginx config
    depends_on:
      - backend
